import React, { useEffect, useState } from 'react';
import { Header } from '../components/layout/Header';
import { DocumentSelector } from '../components/research/DocumentSelector';
import { QuestionInput } from '../components/research/QuestionInput';
import { AnswerPanel } from '../components/research/AnswerPanel';
import { documentService } from '../services/documentService';
import { researchService } from '../services/researchService';
import { Document, AskQuestionResponse } from '../types';
import {
  RotateCcw,
  Sparkles,
  Download,
  BookOpen,
  Layers,
  HelpCircle,
  FileCheck,
} from 'lucide-react';

export const ResearchPage: React.FC = () => {
  const [documents, setDocuments] = useState<Document[]>([]);
  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const [question, setQuestion] = useState('');
  const [lastSubmittedQuestion, setLastSubmittedQuestion] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [response, setResponse] = useState<AskQuestionResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<'qa' | 'synthesis'>('qa');

  useEffect(() => {
    documentService
      .getDocuments()
      .then((docs) => {
        setDocuments(docs);
        const ready = docs.filter((d) => d.status === 'READY');
        if (ready.length > 0 && selectedIds.length === 0) {
          setSelectedIds(ready.slice(0, 3).map((d) => d.id));
        }
      })
      .catch(console.error);
  }, []);

  const handleToggleDoc = (id: string) => {
    setSelectedIds((prev) =>
      prev.includes(id) ? prev.filter((item) => item !== id) : [...prev, id]
    );
  };

  const handleSelectAll = () => {
    const readyIds = documents.filter((d) => d.status === 'READY').map((d) => d.id);
    setSelectedIds(readyIds);
  };

  const handleDeselectAll = () => {
    setSelectedIds([]);
  };

  const handleAskQuestion = async () => {
    if (selectedIds.length === 0 || !question.trim() || isLoading) return;

    try {
      setIsLoading(true);
      setError(null);
      setLastSubmittedQuestion(question.trim());

      const res = await researchService.askQuestion({
        documentIds: selectedIds,
        question: question.trim(),
      });

      setResponse(res);
    } catch (err: any) {
      setError(err.message || 'Failed to query the research assistant. External AI service may be unreachable.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleSynthesizePreset = async (focus: 'executive' | 'methodology' | 'limitations' | 'comparison', label: string) => {
    if (selectedIds.length === 0 || isLoading) return;

    try {
      setIsLoading(true);
      setError(null);
      setLastSubmittedQuestion(`[Synthesis Mode: ${label}]`);

      const res = await researchService.synthesize({
        documentIds: selectedIds,
        focus,
      });

      setResponse(res);
    } catch (err: any) {
      setError(err.message || 'Failed to generate cross-document synthesis.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleClearWorkspace = () => {
    setQuestion('');
    setResponse(null);
    setError(null);
    setLastSubmittedQuestion('');
  };

  const handleExportReport = () => {
    if (!response) return;

    const selectedDocNames = documents
      .filter((d) => selectedIds.includes(d.id))
      .map((d) => `- ${d.fileName}`)
      .join('\n');

    const sourcesText = response.sources
      .map((s, i) => `[${i + 1}] ${s.fileName} (Page ${s.page}):\n> "${s.snippet}"\n`)
      .join('\n');

    const markdown = `# ResearchDesk Academic Synthesis Brief\n\n**Query / Objective:** ${lastSubmittedQuestion}\n**Generated:** ${new Date().toLocaleString()}\n\n## Context Corpus\n${selectedDocNames}\n\n## Synthesized Findings\n${response.answer}\n\n## Numbered Citations & Sources\n${sourcesText}\n\n---\n*Report generated by ResearchDesk Academic Intelligence.*`;

    const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `ResearchDesk_Brief_${Date.now()}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const promptChips = [
    'What are the core methodologies & architectures?',
    'Compare empirical benchmarks & evaluation results',
    'What are the acknowledged limitations & threats to validity?',
    'Synthesize consensus and divergence across authors',
  ];

  return (
    <div className="flex-1 flex flex-col min-w-0 bg-canvas h-screen overflow-hidden">
      <Header
        title="Research Desk"
        subtitle="Cross-document inquiry and evidence synthesis"
        action={
          <div className="flex items-center gap-2">
            {response && (
              <>
                <button
                  onClick={handleExportReport}
                  className="inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-md border border-stone-200 bg-white text-stone-700 text-xs font-medium hover:bg-stone-50 transition-colors shadow-2xs"
                  title="Export markdown research brief"
                >
                  <Download className="w-3.5 h-3.5 text-stone-500" />
                  <span className="hidden sm:inline">Export Brief (.md)</span>
                </button>
                <button
                  onClick={handleClearWorkspace}
                  className="inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-md border border-stone-200 bg-white text-stone-700 text-xs font-medium hover:bg-stone-50 transition-colors shadow-2xs"
                  title="Clear inquiry workspace"
                >
                  <RotateCcw className="w-3.5 h-3.5 text-stone-500" />
                  <span>New Inquiry</span>
                </button>
              </>
            )}
          </div>
        }
      />

      {/* Main Split Layout */}
      <div className="flex-1 flex overflow-hidden p-6 gap-6 max-w-7xl w-full mx-auto">
        {/* Left Column: Context Document Selection */}
        <div className="w-80 shrink-0 h-full flex flex-col">
          <DocumentSelector
            documents={documents}
            selectedIds={selectedIds}
            onToggle={handleToggleDoc}
            onSelectAll={handleSelectAll}
            onDeselectAll={handleDeselectAll}
          />
        </div>

        {/* Right Column: Inquiry Input & Synthesized Findings */}
        <div className="flex-1 h-full flex flex-col gap-4 overflow-y-auto pr-1">
          {/* Mode Switcher */}
          <div className="flex items-center justify-between border-b border-stone-200/80 pb-2">
            <div className="flex items-center gap-2">
              <button
                onClick={() => setActiveTab('qa')}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-colors ${
                  activeTab === 'qa'
                    ? 'bg-stone-900 text-stone-50 font-semibold shadow-2xs'
                    : 'text-stone-600 hover:text-stone-900 hover:bg-stone-100'
                }`}
              >
                <HelpCircle className="w-3.5 h-3.5" />
                <span>Interactive Inquiry</span>
              </button>

              <button
                onClick={() => setActiveTab('synthesis')}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-colors ${
                  activeTab === 'synthesis'
                    ? 'bg-stone-900 text-stone-50 font-semibold shadow-2xs'
                    : 'text-stone-600 hover:text-stone-900 hover:bg-stone-100'
                }`}
              >
                <Layers className="w-3.5 h-3.5" />
                <span>⚡ Multi-Doc Synthesis</span>
              </button>
            </div>

            <span className="text-[11px] text-stone-400 font-mono hidden md:inline">
              {selectedIds.length} active corpus source(s)
            </span>
          </div>

          {/* Mode 1: Interactive Q&A with Prompt Chips */}
          {activeTab === 'qa' && (
            <div className="space-y-3">
              {/* Quick Inquiry Assistance Chips */}
              <div className="flex flex-wrap items-center gap-1.5">
                <span className="text-[10px] uppercase font-mono tracking-wider text-stone-400 mr-1">
                  Suggested Inquiries:
                </span>
                {promptChips.map((chip, idx) => (
                  <button
                    key={idx}
                    type="button"
                    onClick={() => setQuestion(chip)}
                    disabled={isLoading}
                    className="text-[11px] px-2.5 py-1 rounded bg-stone-100/90 hover:bg-stone-200/80 text-stone-700 font-medium transition-colors border border-stone-200/50 truncate max-w-xs disabled:opacity-50"
                  >
                    {chip}
                  </button>
                ))}
              </div>

              <QuestionInput
                question={question}
                onChange={setQuestion}
                onSubmit={handleAskQuestion}
                isLoading={isLoading}
                selectedDocsCount={selectedIds.length}
              />
            </div>
          )}

          {/* Mode 2: Multi-Doc Synthesis Presets */}
          {activeTab === 'synthesis' && (
            <div className="bg-white rounded-lg border border-stone-200/80 p-4 shadow-2xs space-y-3">
              <div>
                <h3 className="text-xs font-semibold text-stone-900">
                  Automated Cross-Document Synthesis Presets
                </h3>
                <p className="text-[11px] text-stone-500">
                  Select an objective to systematically synthesize knowledge across your {selectedIds.length} selected document(s).
                </p>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5 pt-1">
                <button
                  onClick={() => handleSynthesizePreset('executive', 'Executive Academic Summary')}
                  disabled={selectedIds.length === 0 || isLoading}
                  className="p-3 text-left rounded-md border border-stone-200 hover:border-stone-400 hover:bg-stone-50/70 transition-all disabled:opacity-40"
                >
                  <div className="text-xs font-semibold text-stone-900 flex items-center gap-1.5">
                    <BookOpen className="w-3.5 h-3.5 text-stone-700" />
                    <span>Executive Summary</span>
                  </div>
                  <div className="text-[11px] text-stone-500 mt-1">
                    Synthesizes overall breakthroughs, core problem statements, and key contributions.
                  </div>
                </button>

                <button
                  onClick={() => handleSynthesizePreset('methodology', 'Methodology Matrix')}
                  disabled={selectedIds.length === 0 || isLoading}
                  className="p-3 text-left rounded-md border border-stone-200 hover:border-stone-400 hover:bg-stone-50/70 transition-all disabled:opacity-40"
                >
                  <div className="text-xs font-semibold text-stone-900 flex items-center gap-1.5">
                    <Layers className="w-3.5 h-3.5 text-stone-700" />
                    <span>Methodology Comparison</span>
                  </div>
                  <div className="text-[11px] text-stone-500 mt-1">
                    Compares model architectures, empirical datasets, and training configurations.
                  </div>
                </button>

                <button
                  onClick={() => handleSynthesizePreset('comparison', 'Benchmark Trade-offs')}
                  disabled={selectedIds.length === 0 || isLoading}
                  className="p-3 text-left rounded-md border border-stone-200 hover:border-stone-400 hover:bg-stone-50/70 transition-all disabled:opacity-40"
                >
                  <div className="text-xs font-semibold text-stone-900 flex items-center gap-1.5">
                    <FileCheck className="w-3.5 h-3.5 text-stone-700" />
                    <span>Consensus vs Divergence</span>
                  </div>
                  <div className="text-[11px] text-stone-500 mt-1">
                    Highlights where authors concur on findings and where conclusions diverge.
                  </div>
                </button>

                <button
                  onClick={() => handleSynthesizePreset('limitations', 'Limitations & Future Work')}
                  disabled={selectedIds.length === 0 || isLoading}
                  className="p-3 text-left rounded-md border border-stone-200 hover:border-stone-400 hover:bg-stone-50/70 transition-all disabled:opacity-40"
                >
                  <div className="text-xs font-semibold text-stone-900 flex items-center gap-1.5">
                    <Sparkles className="w-3.5 h-3.5 text-stone-700" />
                    <span>Limitations & Gaps</span>
                  </div>
                  <div className="text-[11px] text-stone-500 mt-1">
                    Extracts threats to validity, unhandled corner cases, and open research directions.
                  </div>
                </button>
              </div>
            </div>
          )}

          {/* Results Panel */}
          <div className="flex-1">
            <AnswerPanel
              response={response}
              isLoading={isLoading}
              error={error}
              question={lastSubmittedQuestion}
            />
          </div>
        </div>
      </div>
    </div>
  );
};
